title: Floor Decor
author: Cătălin Mincinoiu
email: vanzari.daminci@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Floor Decor este un showroom online de top din România, cu peste 20 de ani de experiență 
  în design interior şi exterior, care oferă gresie şi faianţă, parchet SPC, accesorii de 
  baie şi piatră naturală de la branduri de renume. Echipa noastră vă stă la dispoziție cu 
  consultanță dedicată pentru a transforma orice spațiu într-o locuință de vis.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://floordecor.ro" # the base hostname & protocol for your site, e.g. http://example.com
lang: ro
locale: ro_RO
logo: /assets/hero-interior-logo.avif
linkedin_username: catalin-mincinoiu-4492a886
linkedin_show_name: Cătălin Mincinoiu

# Build settings
plugins:
  - jekyll-seo-tag

# Default FRONT MATTER
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
